-- Country Supported
INSERT INTO COUNTRY VALUES ('AUS', 'Australia');
INSERT INTO COUNTRY VALUES ('DEU', 'Germany');
INSERT INTO COUNTRY VALUES ('HUN', 'Hungary');
INSERT INTO COUNTRY VALUES ('IND', 'India');
INSERT INTO COUNTRY VALUES ('JPN', 'Japan');
INSERT INTO COUNTRY VALUES ('NZL', 'New Zealand');
INSERT INTO COUNTRY VALUES ('GBR', 'United Kingdom');
INSERT INTO COUNTRY VALUES ('USA', 'United States');


-- Currencies Supported
INSERT INTO CURRENCY VALUES ('USD', 'US Dollar');
INSERT INTO CURRENCY VALUES ('EUR', 'Euro');
INSERT INTO CURRENCY VALUES ('GBP', 'Pounds Sterling');
INSERT INTO CURRENCY VALUES ('NZD', 'New Zealand Dollar');
INSERT INTO CURRENCY VALUES ('AUD', 'Australian Dollar');
INSERT INTO CURRENCY VALUES ('JPY', 'Japanese Yen');
INSERT INTO CURRENCY VALUES ('HUF', 'Hungarian Forint');
INSERT INTO CURRENCY VALUES ('INR', 'Indian Rupee');

