CREATE TABLE IF NOT EXISTS USER_ADDRESS
 (ID LONG NOT NULL auto_increment
 ,ADDRESS_LINE_1 VARCHAR2(32)
 ,ADDRESS_LINE_2 VARCHAR2(32)
 ,ZIP VARCHAR2(32)
 ,STREET VARCHAR2(32)
 ,COUNTRY VARCHAR2(32)
 ,CITY VARCHAR2(32)
 ,USER_ID LONG NOT NULL
 ,PRIMARY KEY (ID)
 );

CREATE TABLE IF NOT EXISTS USER_ACTIVITY
 (ID LONG NOT NULL auto_increment
 ,USER_ID VARCHAR2(32) NOT NULL
 ,FROM_CURRENCY VARCHAR2(32) NOT NULL
 ,TO_CURRENCY VARCHAR2(32) NOT NULL
 ,SOURCE_AMOUNT NUMBER NOT NULL
 ,CONVERTED_AMOUNT NUMBER NOT NULL
 ,CONVERSION_DATE DATE NOT NULL
 ,CREATED_DATE TIMESTAMP
 ,PRIMARY KEY (ID)
 );
 
CREATE TABLE IF NOT EXISTS APPLICATION_USER
 (ID LONG NOT NULL auto_increment 
 ,EMAIL_ID VARCHAR2(32) NOT NULL
 ,PASSWORD VARCHAR2(32) NOT NULL
 ,FIRST_NAME VARCHAR2(32) NOT NULL
 ,LAST_NAME VARCHAR2(32) NOT NULL
 ,USER_ADDRESS_ID LONG
 ,USER_ACTIVITY_ID LONG
  ,DATE_OF_BIRTH DATE
 ,CREATED_DATE DATE
  ,PRIMARY KEY(ID)
  ,FOREIGN KEY(USER_ADDRESS_ID) REFERENCES USER_ADDRESS (ID) ON DELETE CASCADE
  ,FOREIGN KEY(USER_ACTIVITY_ID) REFERENCES USER_ACTIVITY (ID) ON DELETE CASCADE
 );
 
ALTER TABLE USER_ADDRESS ADD FOREIGN KEY 
  (USER_ID) REFERENCES APPLICATION_USER
  (ID);

ALTER TABLE USER_ACTIVITY ADD FOREIGN KEY 
  (USER_ID) REFERENCES APPLICATION_USER
  (ID);
  
CREATE TABLE IF NOT EXISTS COUNTRY
( COUNTRY_CODE VARCHAR2(6) NOT NULL,
  COUNTRY_NAME VARCHAR2(32) NOT NULL,
  PRIMARY KEY (COUNTRY_CODE, COUNTRY_NAME)
);

CREATE TABLE IF NOT EXISTS CURRENCY
( CURRENCY_CODE VARCHAR2(6) NOT NULL,
  CURRENCY_NAME VARCHAR2(32) NOT NULL,
  PRIMARY KEY (CURRENCY_CODE, CURRENCY_NAME)
);
  